"""Canonical public menu data for Biryani House Dordrecht."""

from collections.abc import Sequence

DietaryLabels = Sequence[str]


def category(slug: str, name: str, description: str, sort_order: int) -> dict:
    return {
        "id": f"cat-{slug}",
        "slug": slug,
        "name": name,
        "description": description,
        "sortOrder": sort_order,
    }


CATEGORIES = [
    category(
        "starters",
        "Starters",
        "Warme snacks, soepen en kleine gerechten om samen te delen.",
        1,
    ),
    category("kids", "Kids", "Vertrouwde favorieten voor onze jongste gasten.", 2),
    category(
        "lunch-sides",
        "Lunch / Sides",
        "Krokante bijgerechten, brood en snelle lunchfavorieten.",
        3,
    ),
    category(
        "salads-sauces",
        "Salads & Sauces",
        "Frisse salades, chaat en huisgemaakte sauzen.",
        4,
    ),
    category(
        "biryani",
        "Biryani",
        "Basmati rijst met gedroogde uien, koriander en Indiase/Pakistaanse kruiden.",
        5,
    ),
    category(
        "balti-specialiteiten",
        "Balti Specialiteiten",
        "Rijk gekruide balti-gerechten, vers bereid en warm geserveerd.",
        6,
    ),
    category(
        "rogan-josh-specialiteiten",
        "Rogan Josh Specialiteiten",
        "Aromatische curry's met een volle, kruidige saus.",
        7,
    ),
    category(
        "dansak-specialiteiten",
        "Dansak Specialiteiten",
        "Hartige curry's met de kenmerkende balans van linzen en specerijen.",
        8,
    ),
    category(
        "vegetarian-curries",
        "Vegetarian Curries",
        "Vegetarische curry's met groenten, peulvruchten en paneer.",
        9,
    ),
    category(
        "non-vegetarian-curries",
        "Non-Vegetarian Curries",
        "Klassieke kipcurries en kruidige specialiteiten van de chef.",
        10,
    ),
    category(
        "sweet-curries",
        "Sweet Curries",
        "Romige, mildzoete curry's met rijke specerijen.",
        11,
    ),
    category(
        "main-dishes-bbq-grill",
        "Main Dishes / BBQ Grill",
        "Tandoori, kebab en gegrilde specialiteiten van de barbecue.",
        12,
    ),
    category(
        "thali",
        "Thali",
        "Complete proeverijen met curry's, salade, raita en een zoete afsluiter.",
        13,
    ),
    category(
        "desserts-traditional-drinks",
        "Desserts & Traditional Drinks",
        "Traditionele desserts, chai en verkoelende lassi.",
        14,
    ),
    category("drinks", "Drinks", "Frisdrank, warme dranken, sap en water.", 15),
]


def dish(
    slug: str,
    category_slug: str,
    name: str,
    price_cents: int,
    description: str = "",
    *,
    dietary: DietaryLabels = ("halal",),
    allergens: Sequence[str] = (),
    popular: bool = False,
    spice: int | None = None,
    prep_minutes: int | None = None,
    addons: Sequence[str] = (),
) -> dict:
    return {
        "id": f"item-{slug}",
        "slug": slug,
        "categorySlug": category_slug,
        "name": name,
        "description": description,
        "basePriceCents": price_cents,
        "status": "AVAILABLE",
        "spiceLevel": spice,
        "dietaryLabels": list(dietary),
        "allergenTags": list(allergens),
        "isPopular": popular,
        "prepTimeMinutes": prep_minutes,
        "sortOrder": 1,
        "modifierGroups": [],
        "addonSlugs": list(addons),
    }


ITEMS = [
    # Starters
    dish(
        "starters-chicken-nuggets",
        "starters",
        "Chicken Nuggets (7 stuks)",
        400,
        "Kipnuggets met mayonaise.",
    ),
    dish(
        "chicken-pakora",
        "starters",
        "Chicken Pakora (5 stuks)",
        595,
        "Gefrituurde snack gemaakt van kikkererwtenmeel met kip en kruiden.",
    ),
    dish(
        "chicken-samosa",
        "starters",
        "Chicken Samosa (2 stuks)",
        550,
        "Gefrituurd pasteitje gevuld met kip, groenten en kruiden.",
    ),
    dish(
        "chicken-yakhni",
        "starters",
        "Chicken Yakhni",
        695,
        "Heldere kippensoep met gesauteerde uien en zwarte peper.",
    ),
    dish("starters-french-fries", "starters", "French Fries", 350, "Patat met mayonaise."),
    dish(
        "lamb-yakhni",
        "starters",
        "Lamb Yakhni",
        795,
        "Heldere lamsvleessoep met gesauteerde uien en zwarte peper.",
    ),
    dish(
        "papadum",
        "starters",
        "Papadum",
        200,
        "Gekruide gebakken crackers met dipsauzen.",
        dietary=("vegetarian", "halal"),
    ),
    dish("starters-potato-wedges", "starters", "Potato Wedges", 350, dietary=("vegetarian", "halal")),
    dish(
        "veg-pakora",
        "starters",
        "Veg Pakora (5 stuks)",
        495,
        "Gefrituurde snack met kikkererwtenmeel, kruiden en groenten.",
        dietary=("vegetarian", "halal"),
    ),
    dish(
        "vegetable-samosa",
        "starters",
        "Vegetable Samosa (2 stuks)",
        495,
        "Gefrituurd pasteitje gevuld met aardappel, groenten en kruiden.",
        dietary=("vegetarian", "halal"),
    ),
    # Kids
    dish("kids-chicken-nuggets", "kids", "Chicken Nuggets (7 stuks)", 400),
    dish("kids-french-fries", "kids", "French Fries", 350, dietary=("vegetarian", "halal")),
    dish("kids-potato-wedges", "kids", "Potato Wedges", 350, dietary=("vegetarian", "halal")),
    # Lunch / sides
    dish("lunch-chicken-nuggets", "lunch-sides", "Chicken Nuggets", 399),
    dish("chicken-tenders", "lunch-sides", "Chicken Tenders", 799),
    dish(
        "chili-cheese-nuggets",
        "lunch-sides",
        "Chili Cheese Nuggets",
        599,
        dietary=("vegetarian", "halal"),
    ),
    dish("fries-large", "lunch-sides", "Fries Large", 699, dietary=("vegetarian", "halal")),
    dish("fries-medium", "lunch-sides", "Fries Medium", 499, dietary=("vegetarian", "halal")),
    dish("garlic-bread", "lunch-sides", "Garlic Bread", 399, dietary=("vegetarian", "halal")),
    dish(
        "garlic-bread-cheese",
        "lunch-sides",
        "Garlic Bread With Cheese",
        599,
        dietary=("vegetarian", "halal"),
    ),
    dish("onion-rings", "lunch-sides", "Onion Rings", 499, dietary=("vegetarian", "halal")),
    # Salads & sauces
    dish(
        "chana-chaat",
        "salads-sauces",
        "Chana Chaat",
        550,
        "Kikkererwten met uien, tomaat en pittige kruiden.",
        dietary=("vegetarian", "halal"),
    ),
    dish(
        "fresh-green-salad",
        "salads-sauces",
        "Fresh Green Salad",
        450,
        "IJsbergsla, komkommer, tomaat en appel.",
        dietary=("vegetarian", "halal"),
    ),
    dish("mint-sauce", "salads-sauces", "Mint Sauce", 200, dietary=("vegetarian", "halal")),
    dish(
        "raita",
        "salads-sauces",
        "Raita",
        350,
        "Kruidige yoghurt met diverse groenten.",
        dietary=("vegetarian", "halal"),
    ),
    # Biryani
    dish(
        "bombay-biryani",
        "biryani",
        "Bombay Biryani",
        1450,
        "Met aardappelen, gebakken uien en verse groenten.",
        dietary=("vegetarian", "halal"),
    ),
    dish(
        "chicken-biryani",
        "biryani",
        "Chicken Biryani",
        1650,
        "Gestoomde basmati rijst met kip.",
        popular=True,
        addons=("extra-raita", "garlic-bread-addon", "mango-chutney"),
    ),
    dish(
        "chicken-tikka-biryani",
        "biryani",
        "Chicken Tikka Biryani",
        1750,
        "Gestoomde basmati rijst met BBQ kip.",
        popular=True,
        addons=("extra-raita", "mango-chutney"),
    ),
    dish(
        "king-prawn-biryani",
        "biryani",
        "King Prawn Biryani",
        2050,
        "Gestoomde basmati rijst met grote garnalen.",
    ),
    dish("lamb-biryani", "biryani", "Lamb Biryani", 1895, "Basmati rijst met lamsvlees.", popular=True),
    dish(
        "sultani-biryani",
        "biryani",
        "Sultani Biryani",
        2050,
        "Met chicken tikka, cashewnoten, amandelen en rozijnen.",
        dietary=("contains-nuts", "halal"),
        allergens=("cashew", "almond"),
    ),
    dish(
        "veg-biryani",
        "biryani",
        "Veg Biryani",
        1550,
        "Basmati rijst met verse groenten, raita en pittige saus.",
        dietary=("vegetarian", "halal"),
        popular=True,
        addons=("extra-raita", "mango-chutney"),
    ),
    # Balti
    dish("chicken-balti", "balti-specialiteiten", "Chicken Balti", 1750),
    dish("king-prawn-balti", "balti-specialiteiten", "King Prawn Balti", 2350),
    dish("lamb-balti", "balti-specialiteiten", "Lamb Balti", 1950),
    dish(
        "vegetable-balti",
        "balti-specialiteiten",
        "Vegetable Balti",
        1650,
        dietary=("vegetarian", "halal"),
    ),
    # Rogan Josh
    dish("chicken-rogan-josh", "rogan-josh-specialiteiten", "Chicken Rogan Josh", 1750),
    dish("king-prawn-rogan-josh", "rogan-josh-specialiteiten", "King Prawn Rogan Josh", 2250),
    dish("lamb-rogan-josh", "rogan-josh-specialiteiten", "Lamb Rogan Josh", 1950),
    # Dansak
    dish("chicken-dansak", "dansak-specialiteiten", "Chicken Dansak", 1850),
    dish("king-prawn-dansak", "dansak-specialiteiten", "King Prawn Dansak", 2350),
    dish("lamb-dansak", "dansak-specialiteiten", "Lamb Dansak", 2050),
    dish(
        "vegetable-dansak",
        "dansak-specialiteiten",
        "Vegetable Dansak",
        1700,
        dietary=("vegetarian", "halal"),
    ),
    # Vegetarian curries
    dish(
        "aloo-gobbi",
        "vegetarian-curries",
        "Aloo Gobbi",
        1550,
        "Aardappel en bloemkool curry.",
        dietary=("vegetarian", "halal"),
    ),
    dish(
        "aloo-mattar",
        "vegetarian-curries",
        "Aloo Mattar",
        1550,
        "Aardappel en groene erwten.",
        dietary=("vegetarian", "halal"),
    ),
    dish(
        "aloo-palak",
        "vegetarian-curries",
        "Aloo Palak",
        1550,
        "Spinazie en aardappel curry.",
        dietary=("vegetarian", "halal"),
    ),
    dish(
        "bhindi-karahi",
        "vegetarian-curries",
        "Bhindi Karahi",
        1550,
        "Okra met ui en tomaat.",
        dietary=("vegetarian", "halal"),
    ),
    dish(
        "daal-chana",
        "vegetarian-curries",
        "Daal Chana",
        1550,
        "Gespleten kikkererwten met kruidenolie.",
        dietary=("vegetarian", "halal"),
    ),
    dish(
        "lahori-chana-curry",
        "vegetarian-curries",
        "Lahori Chana Curry",
        1550,
        dietary=("vegetarian", "halal"),
    ),
    dish("mattar-paneer", "vegetarian-curries", "Mattar Paneer", 1550, dietary=("vegetarian", "halal")),
    dish("mix-veg-curry", "vegetarian-curries", "Mix Veg Curry", 1595, dietary=("vegetarian", "halal")),
    dish("palak-paneer", "vegetarian-curries", "Palak Paneer", 1550, dietary=("vegetarian", "halal")),
    # Non-vegetarian curries
    dish("balti-chicken", "non-vegetarian-curries", "Balti Chicken", 1750),
    dish("non-veg-butter-chicken", "non-vegetarian-curries", "Butter Chicken", 1850, popular=True),
    dish("chefs-special-tikka-curry", "non-vegetarian-curries", "Chef’s Special Tikka Curry", 1850),
    dish("chicken-aloo", "non-vegetarian-curries", "Chicken Aloo", 1650),
    dish("chicken-chana", "non-vegetarian-curries", "Chicken Chana", 1650),
    dish("chicken-curry", "non-vegetarian-curries", "Chicken Curry", 1550),
    dish("chicken-do-piazza", "non-vegetarian-curries", "Chicken Do Piazza", 1795),
    dish("chicken-jalfrezi", "non-vegetarian-curries", "Chicken Jalfrezi", 1750),
    dish("chicken-kabab-curry", "non-vegetarian-curries", "Chicken Kabab Curry", 1750),
    dish("chicken-lahori-karahi", "non-vegetarian-curries", "Chicken Lahori Karahi", 1750, popular=True),
    dish("chicken-madras", "non-vegetarian-curries", "Chicken Madras", 1750),
    dish("chicken-makhni", "non-vegetarian-curries", "Chicken Makhni", 1750),
    dish(
        "tandoori-chicken-tikka-curry",
        "non-vegetarian-curries",
        "Tandoori Chicken Tikka Curry",
        1750,
    ),
    # Sweet curries
    dish("sweet-butter-chicken", "sweet-curries", "Butter Chicken", 1850, popular=True),
    dish("chefs-special-tikka-masala", "sweet-curries", "Chef’s Special Tikka Masala", 1950),
    dish("chicken-korma", "sweet-curries", "Chicken Korma", 1650),
    dish("lamb-korma", "sweet-curries", "Lamb Korma", 1750),
    dish(
        "paneer-tikka-masala",
        "sweet-curries",
        "Paneer Tikka Masala",
        1450,
        dietary=("vegetarian", "halal"),
    ),
    dish("tandoori-chicken-tikka-masala", "sweet-curries", "Tandoori Chicken Tikka Masala", 1750),
    # Main dishes / BBQ grill
    dish("bbq-chicken-piece", "main-dishes-bbq-grill", "BBQ Chicken Piece", 1550),
    dish("chicken-seekh-kabab", "main-dishes-bbq-grill", "Chicken Seekh Kabab", 1650),
    dish("lamb-seekh-kabab", "main-dishes-bbq-grill", "Lamb Seekh Kabab", 1850),
    dish(
        "mix-grill",
        "main-dishes-bbq-grill",
        "Mix Grill",
        2450,
        "Chicken tikka, tandoori chicken, lamb seekh kabab and chicken seekh kabab.",
        popular=True,
    ),
    dish("tandoori-chicken-tikka-boti", "main-dishes-bbq-grill", "Tandoori Chicken Tikka Boti", 1650),
    # Thali
    dish(
        "non-veg-thali",
        "thali",
        "Non Veg Thali",
        2150,
        "Kipcurry, lamscurry, groentecurry, salade, raita en gulab jamun.",
    ),
    dish(
        "veg-thali",
        "thali",
        "Veg Thali",
        1950,
        "Palak paneer, groentecurry, daal, salade, raita en gulab jamun.",
        dietary=("vegetarian", "halal"),
    ),
    dish(
        "zoete-thali",
        "thali",
        "Zoete Thali",
        2450,
        "Chicken tikka masala, chicken korma, butter chicken, salade, raita en gulab jamun.",
        popular=True,
    ),
    # Desserts & traditional drinks
    dish("gulab-jamun", "desserts-traditional-drinks", "Gulab Jamun", 180, dietary=("vegetarian", "halal")),
    dish(
        "karak-masala-chai",
        "desserts-traditional-drinks",
        "Karak Chai / Masala Chai",
        400,
        dietary=("vegetarian", "halal"),
    ),
    dish(
        "kashmiri-chai", "desserts-traditional-drinks", "Kashmiri Chai", 450, dietary=("vegetarian", "halal")
    ),
    dish("kheer", "desserts-traditional-drinks", "Kheer", 450, dietary=("vegetarian", "halal")),
    dish(
        "mango-lassi",
        "desserts-traditional-drinks",
        "Mango Lassi",
        450,
        dietary=("vegetarian", "halal"),
        popular=True,
    ),
    dish("salt-lassi", "desserts-traditional-drinks", "Salt Lassi", 350, dietary=("vegetarian", "halal")),
    dish("sweet-lassi", "desserts-traditional-drinks", "Sweet Lassi", 350, dietary=("vegetarian", "halal")),
    # Drinks
    dish("aqua", "drinks", "Aqua", 295, dietary=("vegetarian", "halal")),
    dish("chocomilk", "drinks", "Chocomilk", 295, dietary=("vegetarian", "halal")),
    dish("coca-cola", "drinks", "Coca Cola", 295, dietary=("vegetarian", "halal")),
    dish("coffee", "drinks", "Coffee", 400, dietary=("vegetarian", "halal")),
    dish("energy-drinks", "drinks", "Energy Drinks", 400, dietary=("vegetarian", "halal")),
    dish("fanta", "drinks", "Fanta", 295, dietary=("vegetarian", "halal")),
    dish("fresh-orange-juice", "drinks", "Fresh Orange Juice", 450, dietary=("vegetarian", "halal")),
    dish("juices", "drinks", "Juices", 295, dietary=("vegetarian", "halal")),
    dish("lassis", "drinks", "Lassi’s", 499, dietary=("vegetarian", "halal")),
    dish("lipton-ice-tea", "drinks", "Lipton Ice Tea", 295, dietary=("vegetarian", "halal")),
    dish("mango-drink", "drinks", "Mango Drink", 599, dietary=("vegetarian", "halal")),
    dish(
        "salted-mango-yogurt-drink",
        "drinks",
        "Salted Mango/Yogurt Drink",
        449,
        dietary=("vegetarian", "halal"),
    ),
    dish("soft-drinks", "drinks", "Soft Drinks", 350, dietary=("vegetarian", "halal")),
    dish("sprite", "drinks", "Sprite", 295, dietary=("vegetarian", "halal")),
    dish("tea", "drinks", "Tea", 200, dietary=("vegetarian", "halal")),
    dish("water", "drinks", "Water", 350, dietary=("vegetarian", "halal")),
]
